from typing import Any

class MediaFileUpload:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class MediaIoBaseDownload:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def next_chunk(self) -> tuple[Any, bool]: ...
