openapi: 3.0.0
info:
  title: Inventory Manager API
  version: '1.0'
  description: Central API for inventory insights and reallocation tracking
  contact:
    name: Support
    email: support@example.com
servers:
  - url: http://localhost:5000/api/v1
paths:
  /api/v1/reallocations:
    get:
      summary: List reallocations
      security:
          - bearerAuth: []
      tags: [Reallocation]
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number
        - in: query
          name: size
          schema:
            type: integer
          description: Page size
      responses:
        '200':
          description: List of reallocations
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Reallocation'
                  page:
                    type: integer
                  size:
                    type: integer
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      summary: Create reallocation
      security:
          - bearerAuth: []
      tags: [Reallocation]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sku:
                  type: string
                channel_origin:
                  type: string
                reason:
                  type: string
              required: [sku, channel_origin, reason]
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reallocation'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '409':
          description: Conflict
        '429':
          description: Too many requests
  /api/v1/webhook/shipstation:
    post:
      summary: ShipStation webhook
      tags: [Webhook]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '204':
          description: Accepted
        '400':
          description: Invalid payload or channel
        '403':
          description: Forbidden
        '413':
          description: Payload too large (> 1 024 bytes)
        '429':
          description: Too many requests
        '500':
          description: Server error
  /api/v1/login:
    post:
      summary: User login
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required: [email, password]
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Reallocation:
      type: object
      properties:
        id:
          type: integer
        sku:
          type: string
        channel_origin:
          type: string
        reason:
          type: string
        added_date:
          type: string
          format: date-time
